@startuml

left to right direction

actor "utente autenticato" as UtenteAutenticato
actor "utente non autenticato" as UtenteNonAutenticato

rectangle "Pagina-1" {
    actor "admin" as Admin
    usecase "monitoraggio sistema" as Monitoraggio
    usecase "manutenzione sistema" as Manutenzione
    usecase "visualizzazione dati" as Visualizzazione
    usecase "operazioni utente" as OperazioniUtente
    usecase "operazioni stazione" as OperazioniStazione
    usecase "bici libere" as BiciLibere
    usecase "bici occupate" as BiciOccupate
    usecase "bici da manutenzionare" as BiciDaManutenzionare
    usecase "registrazione" as Registrazione
    usecase "visualizzazione mappa" as VisualizzazioneMappa
    usecase "accesso" as Accesso
    usecase "noleggio" as Noleggio
    usecase "riconsegna" as Riconsegna
    usecase "visualizzazione dati riepilogo" as VisualizzazioneRiepilogo

    UtenteAutenticato --> (Registrazione)
    UtenteAutenticato --> (VisualizzazioneMappa)
    UtenteAutenticato --> (Accesso)
    UtenteAutenticato --> (Noleggio)
    UtenteAutenticato --> (Riconsegna)
    UtenteAutenticato --> (VisualizzazioneRiepilogo)

    UtenteNonAutenticato --> (Registrazione)
    UtenteNonAutenticato --> (VisualizzazioneMappa)
    UtenteNonAutenticato --> (Accesso)
    UtenteNonAutenticato --> (Noleggio)
    UtenteNonAutenticato --> (Riconsegna)
    UtenteNonAutenticato --> (VisualizzazioneRiepilogo)

    Admin --> Monitoraggio
    Admin --> Manutenzione
    Admin --> Visualizzazione
    Admin --> OperazioniUtente
    Admin --> OperazioniStazione
    Admin --> BiciLibere
    Admin --> BiciOccupate
    Admin --> BiciDaManutenzionare

    OperazioniUtente ..> (Registrazione) : include
    OperazioniUtente ..> (Accesso) : include
    OperazioniUtente ..> (Noleggio) : include
    OperazioniUtente ..> (Riconsegna) : include
}

@enduml
